# Generated by Django 6.0.6 on 2026-07-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignments',
            field=models.ManyToManyField(related_name='students', through='assessments.StudentAttempt', to='assessments.scenarioassignment'),
        ),
    ]
