# Generated by Django 6.0.6 on 2026-07-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_assignments'),
        ('assessments', '0002_experienceassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assignments',
            field=models.ManyToManyField(related_name='students', through='assessments.StudentAttempt', to='assessments.experienceassignment'),
        ),
    ]
