# Generated by Django 6.0.6 on 2026-07-13 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_admin', '0002_move_scenario_to_content_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Activity Skill',
                'verbose_name_plural': 'Activity Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublishedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, verbose_name='Package Name')),
                ('output_format', models.CharField(default='.elab', max_length=20, verbose_name='Output Format')),
                ('compression_status', models.CharField(max_length=50, verbose_name='Compression Status')),
                ('include_analytics', models.BooleanField(default=True, verbose_name='Include Analytics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Published Package',
                'verbose_name_plural': 'Published Packages',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Media Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='media_library/', verbose_name='File Field')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='External URL')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=30, verbose_name='Media Type')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='File Size (Bytes)')),
                ('folder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Folder Name')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_studio_media', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Studio Notification',
                'verbose_name_plural': 'Studio Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50, verbose_name='Version Number')),
                ('build_number', models.IntegerField(verbose_name='Build Number')),
                ('release_notes', models.TextField(blank=True, null=True, verbose_name='Release Notes')),
                ('package_size', models.IntegerField(verbose_name='Package Size (Bytes)')),
                ('download_url', models.URLField(blank=True, null=True, verbose_name='Download URL')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published At')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_studio_versions', to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
                ('published_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content_studio.publishedpackage', verbose_name='Published Package')),
            ],
            options={
                'verbose_name': 'Publish Version',
                'verbose_name_plural': 'Publish Versions',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the studio scenario.', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed scenario description.', null=True, verbose_name='Description')),
                ('subject', models.CharField(help_text='The subject, e.g. English, Grammar.', max_length=100, verbose_name='Subject')),
                ('language', models.CharField(help_text='Target instruction language.', max_length=100, verbose_name='Language')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20, verbose_name='Difficulty')),
                ('estimated_duration', models.IntegerField(help_text='Duration of the scenario in minutes.', verbose_name='Estimated Duration')),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True, verbose_name='Thumbnail URL')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_studio_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('grade', models.ForeignKey(help_text='The grade this scenario targets.', on_delete=django.db.models.deletion.CASCADE, related_name='studio_scenarios', to='super_admin.grade', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Studio Scenario',
                'verbose_name_plural': 'Studio Scenarios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='publishedpackage',
            name='scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_package', to='content_studio.scenario', verbose_name='Scenario'),
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Outcome Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='content_studio.scenario', verbose_name='Scenario')),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('learning_objective', models.TextField(blank=True, null=True, verbose_name='Learning Objective')),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes.', verbose_name='Estimated Duration')),
                ('mastery_threshold', models.IntegerField(default=80, help_text='Percentage threshold for completion, e.g. 80.', verbose_name='Mastery Threshold')),
                ('display_order', models.IntegerField(verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('skills', models.ManyToManyField(blank=True, related_name='activities', to='content_studio.activityskill', verbose_name='Skills')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='content_studio.scenario', verbose_name='Scenario')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('screen_type', models.CharField(choices=[('INFORMATION', 'Information'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('QUIZ', 'Quiz'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing')], default='INFORMATION', max_length=30, verbose_name='Screen Type')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=30, verbose_name='Screen Status')),
                ('display_order', models.IntegerField(verbose_name='Display Order')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Flexible Content JSON')),
                ('estimated_duration', models.IntegerField(help_text='Duration in seconds.', verbose_name='Estimated Duration Seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='content_studio.activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='Validation Results JSON')),
                ('total_checks', models.IntegerField(default=0, verbose_name='Total Checks')),
                ('passed', models.IntegerField(default=0, verbose_name='Passed Checks')),
                ('warnings', models.IntegerField(default=0, verbose_name='Warnings Count')),
                ('errors', models.IntegerField(default=0, verbose_name='Errors Count')),
                ('validated_at', models.DateTimeField(auto_now=True, verbose_name='Validated At')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_reports', to='content_studio.scenario', verbose_name='Scenario')),
            ],
            options={
                'verbose_name': 'Validation Report',
                'verbose_name_plural': 'Validation Reports',
                'ordering': ['-validated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('scenario', 'display_order'), name='unique_activity_display_order_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(fields=('activity', 'display_order'), name='unique_screen_display_order_per_activity'),
        ),
    ]
