# Generated by Django 6.0.6 on 2026-07-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted'),
        ),
    ]
