# Generated by Django 6.0.6 on 2026-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0002_scenario_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Filename'),
        ),
        migrations.AddField(
            model_name='media',
            name='stored_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stored Filename'),
        ),
        migrations.AddField(
            model_name='media',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uploaded At'),
        ),
    ]
