# Generated by Django 6.0.6 on 2026-07-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0004_validationreport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishversion',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the .elab file.', max_length=64, null=True, verbose_name='SHA-256 Checksum'),
        ),
        migrations.AddField(
            model_name='publishversion',
            name='file_path',
            field=models.CharField(blank=True, help_text='Absolute path to the .elab file on disk.', max_length=512, null=True, verbose_name='Package File Path'),
        ),
    ]
