# Generated by Django 6.0.6 on 2026-07-18 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0005_publishversion_file_path_checksum'),
        ('super_admin', '0003_delete_publishcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scenario',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='learningoutcome',
            old_name='scenario',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='scenario',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='validationreport',
            old_name='scenario',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='publishedpackage',
            old_name='scenario',
            new_name='experience',
        ),
        migrations.RemoveConstraint(
            model_name='activity',
            name='unique_activity_display_order_per_scenario',
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('experience', 'display_order'), name='unique_activity_display_order_per_experience'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(help_text='The title of the studio experience.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed experience description.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='estimated_duration',
            field=models.IntegerField(help_text='Duration of the experience in minutes.', verbose_name='Estimated Duration'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='grade',
            field=models.ForeignKey(help_text='The grade this experience targets.', on_delete=django.db.models.deletion.CASCADE, related_name='studio_experiences', to='super_admin.grade', verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_studio_experiences', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='content_studio.experience', verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='content_studio.experience', verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_reports', to='content_studio.experience', verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='publishedpackage',
            name='experience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_package', to='content_studio.experience', verbose_name='Experience'),
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Studio Experience', 'verbose_name_plural': 'Studio Experiences'},
        ),
    ]
