# Generated by Django 6.0.6 on 2026-07-30
from django.db import migrations

def seed_skills(apps, schema_editor):
    ActivitySkill = apps.get_model('content_studio', 'ActivitySkill')
    skills = ['listening', 'speaking', 'reading', 'writing', 'grammar']
    for skill_name in skills:
        ActivitySkill.objects.get_or_create(
            name=skill_name,
            defaults={'description': f'{skill_name.capitalize()} skill'}
        )

def reverse_skills(apps, schema_editor):
    ActivitySkill = apps.get_model('content_studio', 'ActivitySkill')
    skills = ['listening', 'speaking', 'reading', 'writing', 'grammar']
    ActivitySkill.objects.filter(name__in=skills).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0006_experience_remove_scenario_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_skills, reverse_skills),
    ]
