# Generated by Django 6.0.6 on 2026-07-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0007_seed_activity_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_type',
            field=models.CharField(choices=[('INFORMATION', 'Information'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('QUIZ', 'Quiz'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing'), ('DIALOGUE', 'Dialogue')], default='INFORMATION', max_length=30, verbose_name='Screen Type'),
        ),
    ]
