# Generated by Django 6.0.6 on 2026-08-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0008_alter_screen_screen_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='pending_release_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Pending Release Notes'),
        ),
        migrations.AddField(
            model_name='experience',
            name='pending_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pending Version'),
        ),
        migrations.AddField(
            model_name='experience',
            name='review_remark',
            field=models.TextField(blank=True, null=True, verbose_name='Review Remark'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
