# Generated by Django 6.0.6 on 2026-08-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0009_experience_pending_release_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('MASTER', 'Master')], default='INTERMEDIATE', max_length=20, verbose_name='Difficulty'),
        ),
    ]
