# Generated by Django 6.0.6 on 2026-08-08
from django.db import migrations

def seed_phonetics(apps, schema_editor):
    ActivitySkill = apps.get_model('content_studio', 'ActivitySkill')
    ActivitySkill.objects.get_or_create(
        name='phonetics',
        defaults={'description': 'Phonetics skill'}
    )

def reverse_phonetics(apps, schema_editor):
    ActivitySkill = apps.get_model('content_studio', 'ActivitySkill')
    ActivitySkill.objects.filter(name='phonetics').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0010_alter_experience_difficulty'),
    ]

    operations = [
        migrations.RunPython(seed_phonetics, reverse_phonetics),
    ]
