# Generated by Django 6.0.6 on 2026-08-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0011_seed_phonetics_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('LISTENING', 'Listening'), ('SPEAKING', 'Speaking'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('GRAMMAR', 'Grammar'), ('VOCABULARY', 'Vocabulary'), ('PHONETICS', 'Phonetics'), ('ASSESSMENT', 'Assessment')], default='LISTENING', max_length=30, verbose_name='Activity Type'),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('ASSESSMENT', 'Assessment')], default='LESSON', max_length=20, verbose_name='Experience Type'),
        ),
        migrations.AddField(
            model_name='experience',
            name='mastery_threshold',
            field=models.IntegerField(default=70, help_text='Mastery threshold percentage required for assessment, e.g. 70.', verbose_name='Mastery Threshold'),
        ),
    ]
