# Generated by Django 6.0.6 on 2026-07-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_move_scenario_to_content_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishContent',
        ),
    ]
