# Generated by Django 6.0.6 on 2026-07-23 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_delete_publishcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishContent',
            fields=[
                ('publish_id', models.AutoField(primary_key=True, serialize=False)),
                ('release_name', models.CharField(max_length=150)),
                ('total_experiences', models.IntegerField(default=0)),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('export_file', models.CharField(blank=True, max_length=255, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.grade')),
            ],
            options={
                'db_table': 'cms_publishcontent',
                'ordering': ['-created_at'],
            },
        ),
    ]
