# Generated by Django 6.0.6 on 2026-07-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_publishcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
