# Generated by Django 6.0.6 on 2026-08-10 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0006_subscriptionplan_schoolsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['sort_order', 'grade_name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='school',
            name='contactEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='schoolAdminId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_administered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='schoolId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the class requirements or standards.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.CharField(help_text='Unique name identifying the class level (up to 50 characters).', max_length=50, unique=True, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='sort_order',
            field=models.IntegerField(help_text='Defines the sequence in which classes are listed.', verbose_name='Sort Order'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('licenseId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('licenseKey', models.CharField(max_length=100, unique=True)),
                ('maxLmsServers', models.IntegerField(default=2)),
                ('concurrentUsersPerServer', models.IntegerField(default=40)),
                ('issueDate', models.DateField(auto_now_add=True)),
                ('expiryDate', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_license', to='super_admin.school')),
            ],
            options={
                'db_table': 'cms_license',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='licenseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_linked', to='super_admin.license'),
        ),
        migrations.CreateModel(
            name='LmsServer',
            fields=[
                ('installationId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('serverName', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=20)),
                ('activationDate', models.DateTimeField(auto_now_add=True)),
                ('lastSyncTime', models.DateTimeField(blank=True, null=True)),
                ('currentCapacity', models.IntegerField(default=0)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_servers', to='super_admin.license')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_servers', to='super_admin.school')),
            ],
            options={
                'db_table': 'cms_lmsserver',
            },
        ),
    ]
