# Generated by Django 6.0.6 on 2026-08-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0007_alter_grade_options_school_contactemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='lan_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
