# Generated by Django 6.0.6 on 2026-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0008_school_lan_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='academic_year',
            field=models.CharField(blank=True, default='2026-2027', max_length=20, null=True),
        ),
    ]
