# Generated by Django 6.1.1 on 2026-10-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0010_license_licenseduration_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsserver',
            name='licenseKey',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lmsserver',
            name='maxUsers',
            field=models.IntegerField(default=40),
        ),
    ]
