# Generated by Django 6.1.1 on 2026-10-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0011_lmsserver_licensekey_lmsserver_maxusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsserver',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmsserver',
            name='licenseDuration',
            field=models.CharField(blank=True, default='1 Year', max_length=50, null=True),
        ),
    ]
