# Generated by Django 6.0.6 on 2026-07-15 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_admin', '0001_initial'),
        ('super_admin', '0003_delete_publishcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_ref', models.CharField(max_length=255)),
                ('scenario_title', models.CharField(max_length=255)),
                ('assigned_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_scenarios', to=settings.AUTH_USER_MODEL)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_assignments', to='school_admin.class')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_assignments', to='super_admin.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_assignments', to='super_admin.school')),
            ],
            options={
                'verbose_name': 'Scenario Assignment',
                'verbose_name_plural': 'Scenario Assignments',
                'db_table': 'cms_scenario_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='STARTED', max_length=20)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('lms_attempt_id', models.CharField(max_length=255, unique=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.scenarioassignment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='super_admin.school')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Attempt',
                'verbose_name_plural': 'Student Attempts',
                'db_table': 'cms_student_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_ref', models.CharField(max_length=255)),
                ('screen_title', models.CharField(max_length=255)),
                ('screen_type', models.CharField(max_length=100)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_responses', to='super_admin.school')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_responses', to='assessments.studentattempt')),
            ],
            options={
                'verbose_name': 'Screen Response',
                'verbose_name_plural': 'Screen Responses',
                'db_table': 'cms_screen_response',
                'ordering': ['attempt', 'screen_ref'],
            },
        ),
        migrations.AddIndex(
            model_name='scenarioassignment',
            index=models.Index(fields=['school', 'synced_at'], name='cms_scenari_school__5de6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattempt',
            index=models.Index(fields=['school', 'synced_at'], name='cms_student_school__293f43_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattempt',
            index=models.Index(fields=['student', 'assignment'], name='cms_student_student_6897d3_idx'),
        ),
        migrations.AddIndex(
            model_name='screenresponse',
            index=models.Index(fields=['school', 'synced_at'], name='cms_screen__school__650eae_idx'),
        ),
    ]
