# Generated by Django 6.0.6 on 2026-07-18 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_assignments'),
        ('assessments', '0001_initial'),
        ('school_admin', '0001_initial'),
        ('super_admin', '0003_delete_publishcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScenarioAssignment',
            new_name='ExperienceAssignment',
        ),
        migrations.RenameField(
            model_name='ExperienceAssignment',
            old_name='scenario_ref',
            new_name='experience_ref',
        ),
        migrations.RenameField(
            model_name='ExperienceAssignment',
            old_name='scenario_title',
            new_name='experience_title',
        ),
        migrations.AlterModelTable(
            name='experienceassignment',
            table='cms_experience_assignment',
        ),
        migrations.RemoveIndex(
            model_name='experienceassignment',
            name='cms_scenari_school__5de6c9_idx',
        ),
        migrations.AddIndex(
            model_name='experienceassignment',
            index=models.Index(fields=['school', 'synced_at'], name='cms_experie_school__ae4aa3_idx'),
        ),
        migrations.AlterField(
            model_name='experienceassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experienceassignment',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_assignments', to='school_admin.class'),
        ),
        migrations.AlterField(
            model_name='experienceassignment',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_assignments', to='super_admin.grade'),
        ),
        migrations.AlterField(
            model_name='experienceassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_assignments', to='super_admin.school'),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.experienceassignment'),
        ),
        migrations.AlterModelOptions(
            name='experienceassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Experience Assignment', 'verbose_name_plural': 'Experience Assignments'},
        ),
    ]
