# Generated by Django 6.0.6 on 2026-07-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_student_grade_student_roll_no_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('student_roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'lms_sync_log',
            },
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(db_index=True, max_length=255)),
                ('activity_id', models.CharField(db_index=True, max_length=255)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_activities', to='teacher.student')),
            ],
            options={
                'verbose_name': 'Activity Report',
                'verbose_name_plural': 'Activity Reports',
                'db_table': 'lms_activity_report',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(db_index=True, max_length=255)),
                ('activity_id', models.CharField(db_index=True, max_length=255)),
                ('screen_id', models.CharField(db_index=True, max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_quizzes', to='teacher.student')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'db_table': 'lms_quiz_attempt',
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(db_index=True, max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_progress', to='teacher.student')),
            ],
            options={
                'verbose_name': 'Student Progress',
                'verbose_name_plural': 'Student Progress',
                'db_table': 'lms_student_progress',
                'unique_together': {('student', 'scenario_id')},
            },
        ),
    ]
