# Generated by Django 6.0.6 on 2026-07-01 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(help_text='Unique name identifying the grade level.', max_length=100, unique=True, verbose_name='Grade Name')),
                ('description', models.TextField(blank=True, help_text='A detailed description of the grade requirements or standards.', verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Defines the sequence in which grades are listed.', verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['sort_order', 'grade_name'],
            },
        ),
        migrations.CreateModel(
            name='LearningExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the learning experience.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed information about the learning experience.', verbose_name='Description')),
                ('objective', models.TextField(blank=True, help_text='Pedagogical goals of this learning experience.', verbose_name='Objective')),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated time to complete the experience (in minutes).', verbose_name='Estimated Duration')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', help_text='Complexity rating of the learning material.', max_length=10, verbose_name='Difficulty')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('TESTING', 'Testing'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Lifecycle state of the learning experience.', max_length=15, verbose_name='Status')),
                ('thumbnail', models.URLField(blank=True, help_text='URL link to the cover/thumbnail image.', max_length=500, null=True, verbose_name='Thumbnail URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('grade', models.ForeignKey(help_text='The grade/level this learning experience belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='learning_experiences', to='cms.grade', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Learning Experience',
                'verbose_name_plural': 'Learning Experiences',
                'ordering': ['grade', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the assessment.', max_length=255, verbose_name='Title')),
                ('instructions', models.TextField(blank=True, help_text='Instructions or guidelines for students before starting.', verbose_name='Instructions')),
                ('passing_marks', models.PositiveIntegerField(help_text='Minimum marks required to pass the assessment.', verbose_name='Passing Marks')),
                ('total_marks', models.PositiveIntegerField(help_text='Total achievable marks for the assessment.', verbose_name='Total Marks')),
                ('display_order', models.PositiveIntegerField(help_text='Sequence in which this assessment is listed.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('experience', models.ForeignKey(help_text='The learning experience this assessment evaluates.', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='cms.learningexperience', verbose_name='Learning Experience')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TRUE_FALSE', 'True or False'), ('MATCH', 'Match Column'), ('FILL_BLANK', 'Fill in the Blank'), ('SHORT_ANSWER', 'Short Answer')], help_text='The type/format of the question.', max_length=20, verbose_name='Question Type')),
                ('question_text', models.TextField(help_text='The text/prompt of the question itself.', verbose_name='Question Text')),
                ('marks', models.PositiveIntegerField(help_text='Marks allocated for answering this question correctly.', verbose_name='Marks')),
                ('display_order', models.PositiveIntegerField(help_text='Sequence of the question within the assessment.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assessment', models.ForeignKey(help_text='The assessment this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cms.assessment', verbose_name='Assessment')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(help_text='The text content of the option.', max_length=255, verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, help_text='Designates whether this is the correct answer.', verbose_name='Is Correct')),
                ('display_order', models.PositiveIntegerField(help_text='Sequence of the option relative to other options in the question.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('question', models.ForeignKey(help_text='The question this option belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cms.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('VIDEO', 'Video'), ('STORY', 'Story'), ('AUDIO', 'Audio'), ('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('GAME', 'Game'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing'), ('MCQ', 'Multiple Choice Question'), ('SUMMARY', 'Summary')], help_text='The type of content or activity block.', max_length=20, verbose_name='Block Type')),
                ('title', models.CharField(help_text='Title of this step.', max_length=255, verbose_name='Title')),
                ('content', models.TextField(blank=True, help_text='The body content, story text, or instruction.', verbose_name='Content')),
                ('media_url', models.URLField(blank=True, help_text='URL link to external video, audio, or image media.', max_length=500, null=True, verbose_name='Media URL')),
                ('display_order', models.PositiveIntegerField(help_text='Sequence in which this step is displayed within the experience.', verbose_name='Display Order')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Dynamic configuration settings for the block (JSON).', verbose_name='Settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('experience', models.ForeignKey(help_text='The learning experience this step belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cms.learningexperience', verbose_name='Learning Experience')),
            ],
            options={
                'verbose_name': 'Experience Step',
                'verbose_name_plural': 'Experience Steps',
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('experience', 'display_order'), name='unique_step_display_order_per_experience')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('experience', 'display_order'), name='unique_assessment_display_order_per_experience'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('assessment', 'display_order'), name='unique_question_display_order_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('question', 'display_order'), name='unique_option_display_order_per_question'),
        ),
    ]
