# Generated by Django 6.0.6 on 2026-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='display_order',
            field=models.IntegerField(help_text='Sequence in which this assessment is listed.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions or guidelines for students before starting.', null=True, verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='passing_marks',
            field=models.IntegerField(blank=True, help_text='Minimum marks required to pass the assessment.', null=True, verbose_name='Passing Marks'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='title',
            field=models.CharField(help_text='Title of the assessment.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='total_marks',
            field=models.IntegerField(help_text='Total achievable marks for the assessment.', verbose_name='Total Marks'),
        ),
        migrations.AlterField(
            model_name='experiencestep',
            name='block_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('STORY', 'Story'), ('AUDIO', 'Audio'), ('VOCABULARY', 'Vocabulary'), ('GRAMMAR_GAME', 'Grammar Game'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing'), ('MCQ', 'Multiple Choice Question'), ('SUMMARY', 'Summary')], help_text='The type of content or activity block.', max_length=30, verbose_name='Block Type'),
        ),
        migrations.AlterField(
            model_name='experiencestep',
            name='content',
            field=models.TextField(blank=True, help_text='The body content, story text, or instruction.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='experiencestep',
            name='display_order',
            field=models.IntegerField(help_text='Sequence in which this step is displayed within the experience.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='experiencestep',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL link to external video, audio, or image media.', max_length=255, null=True, verbose_name='Media URL'),
        ),
        migrations.AlterField(
            model_name='experiencestep',
            name='settings',
            field=models.JSONField(blank=True, help_text='Dynamic configuration settings for the block (JSON).', null=True, verbose_name='Settings'),
        ),
        migrations.AlterField(
            model_name='experiencestep',
            name='title',
            field=models.CharField(help_text='Title of this step.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the grade requirements or standards.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.CharField(help_text='Unique name identifying the grade level (up to 50 characters).', max_length=50, unique=True, verbose_name='Grade Name'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='sort_order',
            field=models.IntegerField(help_text='Defines the sequence in which grades are listed.', verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='learningexperience',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed information about the learning experience.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='learningexperience',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', help_text='Complexity rating of the learning material.', max_length=20, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='learningexperience',
            name='estimated_duration',
            field=models.IntegerField(help_text='Estimated time to complete the experience (in minutes).', verbose_name='Estimated Duration'),
        ),
        migrations.AlterField(
            model_name='learningexperience',
            name='objective',
            field=models.TextField(blank=True, help_text='Pedagogical goals of this learning experience.', null=True, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='learningexperience',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('TESTING', 'Testing'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Lifecycle state of the learning experience.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='learningexperience',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='URL link to the cover/thumbnail image.', max_length=255, null=True, verbose_name='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='learningexperience',
            name='title',
            field=models.CharField(help_text='The title of the learning experience.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='option',
            name='display_order',
            field=models.IntegerField(help_text='Sequence of the option relative to other options in the question.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.TextField(help_text='The text content of the option.', verbose_name='Option Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='display_order',
            field=models.IntegerField(help_text='Sequence of the question within the assessment.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(help_text='Marks allocated for answering this question correctly.', verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TRUE_FALSE', 'True or False'), ('MATCH', 'Match Column'), ('FILL_BLANK', 'Fill in the Blank'), ('SHORT_ANSWER', 'Short Answer')], help_text='The type/format of the question.', max_length=30, verbose_name='Question Type'),
        ),
    ]
