# Generated by Django 6.0.6 on 2026-07-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_assessment_display_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='passing_marks',
            new_name='mastery',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mastery',
            field=models.IntegerField(
                blank=True,
                help_text='Minimum marks required to pass the assessment.',
                null=True,
                verbose_name='Mastery',
            ),
        ),
    ]
