# Generated by Django 6.0.6 on 2026-07-07 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_rename_passing_marks_to_mastery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishContent',
            fields=[
                ('publish_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Publish ID')),
                ('release_name', models.CharField(help_text="e.g., 'Grade 6 - July Release'", max_length=100, verbose_name='Release Name')),
                ('total_scenarios', models.IntegerField(help_text='Number of scenarios included', verbose_name='Total Scenarios')),
                ('published_at', models.DateTimeField(blank=True, help_text='Publish date and time', null=True, verbose_name='Published At')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('export_file', models.CharField(blank=True, help_text='Path to generated export package (ZIP/JSON)', max_length=255, null=True, verbose_name='Export File')),
                ('checksum', models.CharField(blank=True, help_text='Integrity verification hash', max_length=64, null=True, verbose_name='Checksum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('grade', models.ForeignKey(db_column='grade_id', on_delete=django.db.models.deletion.CASCADE, related_name='publish_contents', to='cms.grade', verbose_name='Grade')),
                ('published_by', models.ForeignKey(db_column='published_by', on_delete=django.db.models.deletion.CASCADE, related_name='published_contents', to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
            ],
            options={
                'verbose_name': 'Publish Content',
                'verbose_name_plural': 'Publish Contents',
                'ordering': ['-created_at'],
            },
        ),
    ]
