# Generated by Django 6.0.6 on 2026-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_school_class_teacher_teacherclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
