# Generated by Django 6.0.6 on 2026-07-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_class_updated_at_school_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessment',
            name='unique_assessment_display_order_per_experience',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_question_display_order_per_assessment',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
