# Generated by Django 6.0.6 on 2026-08-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_student_grade_student_roll_no_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
